require('xhan.telescop')
require('xhan.lspconfig')
require('xhan.indent')
require('xhan.bufferline')
require('xhan.lualine')
require('xhan.tree')
require('xhan.treesitter')
require('xhan.lspkind')
require('xhan.lsp-colors')
require('xhan.nvim-autopairs')
require('xhan.lsp-saga')
-- require('xhan.githubtheme')
require('xhan.tokyonight')
require('xhan.toggleterm')
